spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nwt_game
    username: postgres
    password: password
  jpa:
    properties:
      dialect:
        hibernate: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update

app:
